#cloud-config

hostname: ${hostname}

fs_setup:
  - label: rancher-data
    filesystem: xfs
    device: /dev/vdb

write_files:
  - path: /opt/rancher/docker-compose.yml
    encoding: b64
    content: ${docker_compose_file}
mounts:
  - [vdb, /opt/rancher/data, xfs, defaults, "0", "0"]

runcmd:
  # fix https://git.centos.org/centos/kickstarts/pull-request/12#
  - sed -i '/^nameserver 192\.168\.122\.1/d' /etc/resolv.conf
  # update system
  - dnf update -y
  # install docker-ce and docker-compose
  - dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  - dnf install -y --nobest docker-ce iptables python3
  - systemctl enable --now docker
  - pip3 install docker-compose
  # start rancher server
  - cd /opt/rancher
  - /usr/local/bin/docker-compose up -d
%{ for cmd in post_commands }
  - ${cmd}
%{ endfor }
