#cloud-config

hostname: ${hostname}

fs_setup:
  - label: rancher-data
    filesystem: xfs
    device: /dev/vdb

write_files:
  - path: /opt/rancher/docker-compose.yml
    encoding: b64
    content: ${docker_compose_file}
  - path: /opt/rancher/backup/docker-compose.yml
    encoding: b64
    content: ${backup_docker_compose_file}
  - path: /opt/rancher/backup/config.json
    mode: "0600"
    encoding: b64
    content: ${backup_config}
  - path: /opt/rancher/backup/entrypoint.sh
    mode: "0755"
    encoding: b64
    content: ${backup_entrypoint}

mounts:
  - [vdb, /opt/rancher/data, xfs, defaults, "0", "0"]

packages:
  - python3
  - ipa-client

runcmd:
  - ipa-client-install -U --mkhomedir --force-join -w ${ipa_otp}
  - dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  - dnf install docker-ce --nobest -y
  - systemctl enable --now docker
  - pip3 install docker-compose
  - cd /opt/rancher
  - /usr/local/bin/docker-compose up -d
