#cloud-config

hostname: ${hostname}

mounts:
  - [/dev/vdb, /opt/rancher/data, xfs, ""]

write_files:
  - content: ${docker_compose_file}
    path: /opt/rancher/docker-compose.yml
    encoding: b64
    owner: root:root
    permissions: "0644"
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      cd /opt/rancher
      /usr/local/bin/docker-compose up -d

runcmd:
  - mkdir -p /usr/local/bin
  - wget "https://github.com/docker/compose/releases/download/1.27.3/docker-compose-$(uname -s)-$(uname -m)" -O /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - echo "PATH=$PATH:/usr/local/bin" > /home/rancher/.bash_profile
