version: "2"

services:
  server:
    image: ${rancher_image}:${rancher_version}
    restart: unless-stopped
    privileged: true
    volumes:
      - /opt/rancher/data/ssl:/etc/rancher/ssl:z
      - /opt/rancher/data/lib:/var/lib/rancher:z
    ports:
      - 80:80
      - 443:443
